server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

spring:
  application:
    name: discovery
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://config:8888}